package com.cgi.praktika.movie.business.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class MovieSchedule {
    public static List<Movie> getMovies() {
        return new ArrayList<>(Arrays.asList(
                //Monday scheduled movies
                new Movie(1, "Dune: Part Two", StartTime.TIME_9_00,
                        Genre.SCIFI, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.MONDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8157/landscape_fullhd/Dune2_Apollo_EHDh_3840x2160.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(2, "The Beekeeper", StartTime.TIME_10_00,
                        Genre.ACTION, AgeRestriction.ALLA_14_KEELATUD,
                        Language.ENGLISH, WeekDay.MONDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8573/landscape_fullhd/Beekeeper_Apollo_EHDh_3840x2160_EE.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(3, "Kung Fu Panda 4", StartTime.TIME_10_00,
                        Genre.FAMILY, AgeRestriction.PEREFILM,
                        Language.ENGLISH, WeekDay.MONDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8705/landscape_fullhd/KungFuPanda4_3840x2160.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(4, "Anyone But You", StartTime.TIME_11_00,
                        Genre.COMEDY, AgeRestriction.ALLA_12_KEELATUD,
                        Language.ENGLISH, WeekDay.MONDAY,
                        "https://movies.sterkinekor.co.za/CDN/media/entity/get/FilmTitleGraphic/HO00002873?referenceScheme=HeadOffice&allowPlaceHolder=true"),
                new Movie(5, "Elu ja armastus", StartTime.TIME_17_00,
                        Genre.DRAMA, AgeRestriction.ALLA_12,
                        Language.ESTONIAN, WeekDay.MONDAY,
                        "https://mcswebsites.blob.core.windows.net/1013/Event_8883/gallery/Elu_ja_armastus_id50_3840x2880px.jpg"),
                new Movie(6, "Migration", StartTime.TIME_19_00,
                        Genre.CARTOON, AgeRestriction.LUBATUD_KOIGILE,
                        Language.ENGLISH, WeekDay.MONDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8424/landscape_fullhd/Migration_3840x2160.jpg?width=640&height=360&format=jpg&quality=90"),
                //Tuesday scheduled movies
                new Movie(7, "Dune: Part Two", StartTime.TIME_9_00,
                        Genre.SCIFI, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.TUESDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8157/landscape_fullhd/Dune2_Apollo_EHDh_3840x2160.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(8, "Kung Fu Panda 4", StartTime.TIME_10_00,
                        Genre.FAMILY, AgeRestriction.PEREFILM,
                        Language.ENGLISH, WeekDay.TUESDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8705/landscape_fullhd/KungFuPanda4_3840x2160.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(9, "The Beekeeper", StartTime.TIME_11_00,
                        Genre.ACTION, AgeRestriction.ALLA_14_KEELATUD,
                        Language.ENGLISH, WeekDay.TUESDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8573/landscape_fullhd/Beekeeper_Apollo_EHDh_3840x2160_EE.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(10, "Anyone But You", StartTime.TIME_11_00,
                        Genre.COMEDY, AgeRestriction.ALLA_12_KEELATUD,
                        Language.ENGLISH, WeekDay.TUESDAY,
                        "https://movies.sterkinekor.co.za/CDN/media/entity/get/FilmTitleGraphic/HO00002873?referenceScheme=HeadOffice&allowPlaceHolder=true"),
                new Movie(11, "Migration", StartTime.TIME_19_00,
                        Genre.CARTOON, AgeRestriction.LUBATUD_KOIGILE,
                        Language.ENGLISH, WeekDay.TUESDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8424/landscape_fullhd/Migration_3840x2160.jpg?width=640&height=360&format=jpg&quality=90"),
                new Movie(12, "Elu ja armastus", StartTime.TIME_17_00,
                        Genre.DRAMA, AgeRestriction.ALLA_12,
                        Language.ESTONIAN, WeekDay.TUESDAY,
                        "https://mcswebsites.blob.core.windows.net/1013/Event_8883/gallery/Elu_ja_armastus_id50_3840x2880px.jpg"),
                // Add more movies for Wednesday, Thursday, Friday, Saturday, and Sunday...
                //Wednesday scheduled movies
                new Movie(13, "Migration", StartTime.TIME_9_00,
                        Genre.CARTOON, AgeRestriction.LUBATUD_KOIGILE,
                        Language.ENGLISH, WeekDay.WEDNESDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8424/landscape_fullhd/Migration_3840x2160.jpg?width=640&height=360&format=jpg&quality=90"),
                new Movie(14, "Elu ja armastus", StartTime.TIME_10_00,
                        Genre.DRAMA, AgeRestriction.ALLA_12,
                        Language.ESTONIAN, WeekDay.WEDNESDAY,
                        "https://mcswebsites.blob.core.windows.net/1013/Event_8883/gallery/Elu_ja_armastus_id50_3840x2880px.jpg"),
                new Movie(15, "Anyone But You", StartTime.TIME_11_00,
                        Genre.COMEDY, AgeRestriction.ALLA_12_KEELATUD,
                        Language.ENGLISH, WeekDay.WEDNESDAY,
                        "https://movies.sterkinekor.co.za/CDN/media/entity/get/FilmTitleGraphic/HO00002873?referenceScheme=HeadOffice&allowPlaceHolder=true"),
                new Movie(16, "Kung Fu Panda 4", StartTime.TIME_12_00,
                        Genre.FAMILY, AgeRestriction.PEREFILM,
                        Language.ENGLISH, WeekDay.WEDNESDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8705/landscape_fullhd/KungFuPanda4_3840x2160.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(17, "The Beekeeper", StartTime.TIME_15_00,
                        Genre.ACTION, AgeRestriction.ALLA_14_KEELATUD,
                        Language.ENGLISH, WeekDay.WEDNESDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8573/landscape_fullhd/Beekeeper_Apollo_EHDh_3840x2160_EE.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(18, "Dune: Part Two", StartTime.TIME_18_00,
                        Genre.SCIFI, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.WEDNESDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8157/landscape_fullhd/Dune2_Apollo_EHDh_3840x2160.jpg?width=960&height=540&format=jpg&quality=90"),
                //Thursday scheduled movies
                new Movie(19, "Dune: Part Two", StartTime.TIME_9_00,
                        Genre.SCIFI, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.THURSDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8157/landscape_fullhd/Dune2_Apollo_EHDh_3840x2160.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(20, "The Beekeeper", StartTime.TIME_10_00,
                        Genre.ACTION, AgeRestriction.ALLA_14_KEELATUD,
                        Language.ENGLISH, WeekDay.THURSDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8573/landscape_fullhd/Beekeeper_Apollo_EHDh_3840x2160_EE.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(21, "Kung Fu Panda 4", StartTime.TIME_10_00,
                        Genre.FAMILY, AgeRestriction.PEREFILM,
                        Language.ENGLISH, WeekDay.THURSDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8705/landscape_fullhd/KungFuPanda4_3840x2160.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(22, "Anyone But You", StartTime.TIME_11_00,
                        Genre.COMEDY, AgeRestriction.ALLA_12_KEELATUD,
                        Language.ENGLISH, WeekDay.THURSDAY,
                        "https://movies.sterkinekor.co.za/CDN/media/entity/get/FilmTitleGraphic/HO00002873?referenceScheme=HeadOffice&allowPlaceHolder=true"),
                new Movie(23, "Elu ja armastus", StartTime.TIME_17_00,
                        Genre.DRAMA, AgeRestriction.ALLA_12,
                        Language.ESTONIAN, WeekDay.THURSDAY,
                        "https://mcswebsites.blob.core.windows.net/1013/Event_8883/gallery/Elu_ja_armastus_id50_3840x2880px.jpg"),
                new Movie(24, "Migration", StartTime.TIME_19_00,
                        Genre.CARTOON, AgeRestriction.LUBATUD_KOIGILE,
                        Language.ENGLISH, WeekDay.THURSDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8424/landscape_fullhd/Migration_3840x2160.jpg?width=640&height=360&format=jpg&quality=90"),
                //Friday scheduled movies
                new Movie(25, "Dune: Part Two", StartTime.TIME_9_00,
                        Genre.SCIFI, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.FRIDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8157/landscape_fullhd/Dune2_Apollo_EHDh_3840x2160.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(26, "Kung Fu Panda 4", StartTime.TIME_10_00,
                        Genre.FAMILY, AgeRestriction.PEREFILM,
                        Language.ENGLISH, WeekDay.FRIDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8705/landscape_fullhd/KungFuPanda4_3840x2160.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(27, "The Beekeeper", StartTime.TIME_11_00,
                        Genre.ACTION, AgeRestriction.ALLA_14_KEELATUD,
                        Language.ENGLISH, WeekDay.FRIDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8573/landscape_fullhd/Beekeeper_Apollo_EHDh_3840x2160_EE.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(28, "Anyone But You", StartTime.TIME_11_00,
                        Genre.COMEDY, AgeRestriction.ALLA_12_KEELATUD,
                        Language.ENGLISH, WeekDay.FRIDAY,
                        "https://movies.sterkinekor.co.za/CDN/media/entity/get/FilmTitleGraphic/HO00002873?referenceScheme=HeadOffice&allowPlaceHolder=true"),
                new Movie(29, "Migration", StartTime.TIME_19_00,
                        Genre.CARTOON, AgeRestriction.LUBATUD_KOIGILE,
                        Language.ENGLISH, WeekDay.FRIDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8424/landscape_fullhd/Migration_3840x2160.jpg?width=640&height=360&format=jpg&quality=90"),
                new Movie(30, "Elu ja armastus", StartTime.TIME_17_00,
                        Genre.DRAMA, AgeRestriction.ALLA_12,
                        Language.ESTONIAN, WeekDay.FRIDAY,
                        "https://mcswebsites.blob.core.windows.net/1013/Event_8883/gallery/Elu_ja_armastus_id50_3840x2880px.jpg"),
                //Saturday scheduled movies
                new Movie(31, "Migration", StartTime.TIME_9_00,
                        Genre.CARTOON, AgeRestriction.LUBATUD_KOIGILE,
                        Language.ENGLISH, WeekDay.SATURDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8424/landscape_fullhd/Migration_3840x2160.jpg?width=640&height=360&format=jpg&quality=90"),
                new Movie(32, "Elu ja armastus", StartTime.TIME_10_00,
                        Genre.DRAMA, AgeRestriction.ALLA_12,
                        Language.ESTONIAN, WeekDay.SATURDAY,
                        "https://mcswebsites.blob.core.windows.net/1013/Event_8883/gallery/Elu_ja_armastus_id50_3840x2880px.jpg"),
                new Movie(33, "Anyone But You", StartTime.TIME_11_00,
                        Genre.COMEDY, AgeRestriction.ALLA_12_KEELATUD,
                        Language.ENGLISH, WeekDay.SATURDAY,
                        "https://movies.sterkinekor.co.za/CDN/media/entity/get/FilmTitleGraphic/HO00002873?referenceScheme=HeadOffice&allowPlaceHolder=true"),
                new Movie(34, "Kung Fu Panda 4", StartTime.TIME_12_00,
                        Genre.FAMILY, AgeRestriction.PEREFILM,
                        Language.ENGLISH, WeekDay.SATURDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8705/landscape_fullhd/KungFuPanda4_3840x2160.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(35, "The Beekeeper", StartTime.TIME_15_00,
                        Genre.ACTION, AgeRestriction.ALLA_14_KEELATUD,
                        Language.ENGLISH, WeekDay.SATURDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8573/landscape_fullhd/Beekeeper_Apollo_EHDh_3840x2160_EE.jpg?width=960&height=540&format=jpg&quality=90"),
                new Movie(36, "Dune: Part Two", StartTime.TIME_18_00,
                        Genre.SCIFI, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.SATURDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8157/landscape_fullhd/Dune2_Apollo_EHDh_3840x2160.jpg?width=960&height=540&format=jpg&quality=90"),
                //Sunday scheduled movies
                new Movie(37, "The Royal Ballet - Swan Lake", StartTime.TIME_9_00,
                        Genre.DRAMA, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.SUNDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8541/landscape_qhd/ROHCinema_International-English.jpg?width=1280&height=720&format=jpg&quality=90"),
                new Movie(38, "The Royal Ballet - Swan Lake", StartTime.TIME_10_00,
                        Genre.DRAMA, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.SUNDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8541/landscape_qhd/ROHCinema_International-English.jpg?width=1280&height=720&format=jpg&quality=90"),
                new Movie(39, "The Royal Ballet - Swan Lake", StartTime.TIME_11_00,
                        Genre.DRAMA, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.SUNDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8541/landscape_qhd/ROHCinema_International-English.jpg?width=1280&height=720&format=jpg&quality=90"),
                new Movie(40, "The Royal Ballet - Swan Lake", StartTime.TIME_12_00,
                        Genre.DRAMA, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.SUNDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8541/landscape_qhd/ROHCinema_International-English.jpg?width=1280&height=720&format=jpg&quality=90"),
                new Movie(41, "The Royal Ballet - Swan Lake", StartTime.TIME_13_00,
                        Genre.DRAMA, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.SUNDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8541/landscape_qhd/ROHCinema_International-English.jpg?width=1280&height=720&format=jpg&quality=90"),
                new Movie(42, "The Royal Ballet - Swan Lake", StartTime.TIME_14_00,
                        Genre.DRAMA, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.SUNDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8541/landscape_qhd/ROHCinema_International-English.jpg?width=1280&height=720&format=jpg&quality=90"),
                new Movie(43, "The Royal Ballet - Swan Lake", StartTime.TIME_15_00,
                        Genre.DRAMA, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.SUNDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8541/landscape_qhd/ROHCinema_International-English.jpg?width=1280&height=720&format=jpg&quality=90"),
                new Movie(44, "The Royal Ballet - Swan Lake", StartTime.TIME_16_00,
                        Genre.DRAMA, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.SUNDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8541/landscape_qhd/ROHCinema_International-English.jpg?width=1280&height=720&format=jpg&quality=90"),
                new Movie(45, "The Royal Ballet - Swan Lake", StartTime.TIME_17_00,
                        Genre.DRAMA, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.SUNDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8541/landscape_qhd/ROHCinema_International-English.jpg?width=1280&height=720&format=jpg&quality=90"),
                new Movie(46, "The Royal Ballet - Swan Lake", StartTime.TIME_18_00,
                        Genre.DRAMA, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.SUNDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8541/landscape_qhd/ROHCinema_International-English.jpg?width=1280&height=720&format=jpg&quality=90"),
                new Movie(47, "The Royal Ballet - Swan Lake", StartTime.TIME_19_00,
                        Genre.DRAMA, AgeRestriction.LUBATUD_KOIGILE,
                        Language.MULTILINGUAL, WeekDay.SUNDAY,
                        "https://images.markus.live/mcswebsites.blob.core.windows.net/1013/Event_8541/landscape_qhd/ROHCinema_International-English.jpg?width=1280&height=720&format=jpg&quality=90")
        ));
    }
}
